include:
  - board: seeeduino_xiao_ble
    shield: hivekb_left
  - board: seeeduino_xiao_ble
    shield: hivekb_right
  - board: seeeduino_xiao_ble
    shield: hivekb_left rgbled_adapter
  - board: seeeduino_xiao_ble
    shield: hivekb_right rgbled_adapter
